fix service, bumb autoconf dependency

diff --git a/templates/nutcracker.erb b/templates/nutcracker.erb
--- a/templates/nutcracker.erb
+++ b/templates/nutcracker.erb
@@ -5,19 +5,24 @@
 # Required-Stop:     $network $remote_fs $local_fs
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: Stop/start nutcracker <%= @name %>
+# Short-Description: Stop/start <%= @name %>
 ### END INIT INFO
 
 PATH=/sbin:/usr/sbin:/bin:/usr/bin
 DESC=<%= @name %>
 NAME=<%= @name %>
-CONFFILE=/etc/nutcracker/<%= @name %>.yml
-LOGFILE=/var/log/nutcracker/<%= @name %>.log
+USER=nobody
+GROUP=nogroup
+CONFFILE=<%= @conf_dir %>/<%= @name %>.yml
+LOGFILE=<%= @log_dir %>/<%= @name %>.log
 DAEMON=/usr/sbin/nutcracker
-PIDFILE=/var/run/nutcracker/$NAME.pid
-DAEMON_ARGS="-c $CONFFILE -o $LOGFILE -p $PIDFILE -s <%= @statsport %> -d"
-#DAEMON_ARGS="-c $CONFFILE -p $PIDFILE -s <%= @statsport %> -d"
+PIDFILE=<%= @pid_dir %>/${NAME}.pid
+STATSPORT=<%= @statsport %>
+DAEMON_ARGS="-c $CONFFILE -o $LOGFILE -p $PIDFILE -s $STATSPORT -v <%= @verbosity %> -m 2048 -d"
 SCRIPTNAME=/etc/init.d/$NAME
+
+ulimit -Hn 100000
+ulimit -Sn 100000
 
 [ -x $DAEMON ] || exit 0
 
@@ -29,9 +34,20 @@ SCRIPTNAME=/etc/init.d/$NAME
 
 do_start()
 {
-    start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
+    mkdir -p <%= @pid_dir %>
+    touch $PIDFILE
+    chown $USER:$GROUP -R <%= @pid_dir %>
+    chmod 755 <%= @pid_dir %>
+    echo -n "Starting ${NAME}: "
+    start-stop-daemon --start --quiet -m --pidfile $PIDFILE --chuid $USER:$GROUP --exec $DAEMON -- \
         $DAEMON_ARGS
     RETVAL="$?"
+
+    case "$RETVAL" in
+        0|1) echo "STARTED." ;;
+        2) echo "FAILED." ;;
+    esac
+    
     return "$RETVAL"
 }
 
@@ -43,9 +59,14 @@ do_stop()
     #   2 if daemon could not be stopped
     #   other if a failure occurred
 
-    kill -9 `cat ${PIDFILE}`
+    echo -n "Stopping ${NAME}: "
+    start-stop-daemon --stop --quiet --pidfile $PIDFILE --exec $DAEMON || true
+
     RETVAL="$?"
-    rm -f ${PIDFILE}
+    case "$RETVAL" in
+        0|1) echo "STOPPED." ;;
+        2) echo "FAILED." ;;
+    esac
     return "$RETVAL"
 }
 
@@ -67,18 +88,10 @@ case "$1" in
         esac
         ;;
     status)
-        ps -ef | grep `cat ${PIDFILE}`
-        case "$?" in
-            0|1)
-                echo "Twemproxy ${NAME} is running..."
-            ;;
-            2)
-                echo "Twemproxy ${NAME} isn't running..."
-            ;;
-         esac
+        status_of_proc -p $PIDFILE "$DAEMON" "${NAME}" && exit 0 || exit $?
         ;;
     restart)
-        log_daemon_msg "Restarting $DESC" "$NAME"
+        log_daemon_msg "Restarting $DESC" "${NAME}"
         do_stop
         echo "Twemproxy has stopped..."
         do_start
